### ISSUE TITLE
Schedule - now playing, up next?

### ISSUE THREAD

**Issue by bryanharley** [trms/wp-cablecast#12]
How can I display what's playing right now and what's coming up next?

**Comment by bryanharley** [comment]
Figured it out! ... with the help of Ray.

[schedule-upnext1.txt](https://github.com/raytiley/wp-cablecast/files/3025147/schedule-upnext1.txt)

**Comment by raytiley** [comment]
@bryanharley - wanna update the readme a FAQ on this? I could see it being a common question.

**Comment by bryanharley** [comment]
OK done
