### ISSUE TITLE
EventDate change doesn't sync to WP post_date

### ISSUE THREAD

**Issue by bryanharley** [trms/wp-cablecast#15]
Upon syncing, the Cablecast show's EventDate becomes the WordPress post's publish date (post_date).  However, I noticed that if I go back to change the Event Date on Cablecast, upon the next sync it does update the custom field post meta, but it **does not** update the actual post_date.

**Comment by bryanharley** [comment]
I don't know how to fix this bug, but it's annoying.   :(

**Comment by raytiley** [comment]
This is conscious decision when I designed the plugin. Basically I don't want Cablecast to fight over control of Wordpress fields.  My thought was you may use the wordpress date to say control when a show becomes visible on your site and that might be different from the event date in Cablecast. I think it's common they are the same, but if you change the publish date in wordpress I don't want Cablecast changing it back every time it syncs.

The way I would typically solve these types of customizations is with a second plugin that acts when ever a Cablecast show is going to change. This is where you could put things like always taking the custom meta and setting the post date for Cablecast Show content types.

I can try to whip up a dummy plugin as an example with this type of customization.

**Comment by bryanharley** [comment]
Hm. I see your point. For how we use it, I would much rather have Cablecast control the post's publish date. 

Instead of a second plugin, you could implement this as an option on the settings page. "Always Sync EventDate Changes? Yes or No".  Let the user decide.

**Comment by bryanharley** [comment]
Fixed by https://github.com/trms/wp-cablecast/pull/31
