### ISSUE TITLE
CG Title change doesn't sync to WP slug

### ISSUE THREAD

**Issue by bryanharley** [trms/wp-cablecast#19]
Upon syncing, the Cablecast show's CG Title becomes the WordPress post's title and slug.  However, I noticed that if I go back and modify the CG Title on Cablecast, upon the next sync it **does not** update the slug.

**Comment by raytiley** [comment]
Wouldn't this break the links, or would wordpress handle a redirect?

**Comment by bryanharley** [comment]
When the slug changes, WP automatically 301 redirects it.

**Comment by bryanharley** [comment]
Upon further research, this shouldn't happen automagically. Slugs should be updated manually. So I'm closing this.
