### ISSUE TITLE
`pre_get_posts` hook hiding nav menus on archive pages

### ISSUE THREAD

**Issue by superlou** [trms/wp-cablecast#25]
The following hook modifies the query so that an archive page includes both post and show types:

https://github.com/trms/wp-cablecast/blob/bcabf82d41484fb3353ad3f29bd80188434e3b7f/display.php#L3-L15

For some reason, `$post_type = get_query_var('post_type')` is failing to find the post type for navigation menu queries, which is something like `$query['query_vars']['post_type'] = 'nav_menu_item'`. Because it doesn't see a post type, it then writes over the `post_type` to be only posts and shows. This makes the menu fail to load.

I'm still trying to figure out the right way to fix this. As a hack, you can do `$post_type = array('nav_menu_item', 'post','show');`, but I'm afraid that recently created navigation menu items might start showing up in archives.

Edit: `$post_type = $query->get('post_type');` seems to work, but I'm not sure why `get_query_var` isn't working.

**Comment by bryanharley** [comment]
I reported this here: https://github.com/trms/wp-cablecast/issues/4.

I'm using the "hack" to fix it. There was a discussion on the WP forums about this too, it's a weird issue with custom post types.

**Comment by superlou** [comment]
Whoops, sorry for the duplicate. I agree this is definitely #4.
