### ISSUE TITLE
Tags custom field doesn't sync correctly

### ISSUE THREAD

**Issue by bryanharley** [trms/wp-cablecast#29]
The new "tags" type of custom field introduced in 7.2 does not sync correctly to WordPress.  For example, in Cablecast I created a "Tags" custom field called "Tags."  I added the tag "Valentine's Day" to a show.  On the WordPress side, the post metadata is created with "Tags" as the key, but the value is "1".  So something is broken (looks like this is the number of tags, I added another and it changed to 2).  But also, I think importing "tags" as WP post metadata doesn't make sense.  This should be implemented differently. 

If a "Tags" type custom field exists on Cablecast, it should instead be [registered as a new tag taxonomy](https://developer.wordpress.org/plugins/taxonomies/working-with-custom-taxonomies/) for the 'show' custom post type.

**Comment by raytiley** [comment]
This is a good idea... The tags custom field was added most of the code in this plugin was written. I'll add it to the todo list.

**Comment by bryanharley** [comment]
Registering the new "Cablecast Tags" taxonomy is easy enough.  But I was looking at how you sync custom fields from Cablecast and "FieldDefinitions", but I don't really see how to confirm if a custom field is a "tag" type.  https://yourtown.cablecast.tv/CablecastAPI/documentation

**Comment by bryanharley** [comment]
#37 - works great!
