### ISSUE TITLE
Show first runs for a given week?

### ISSUE THREAD

**Issue by bryanharley** [trms/wp-cablecast#36]
Trying to figure out how to display a list of shows that have their first scheduled run in a given week.  We create this page manually each Monday, but I'm thinking there should be a way to do this automagically: https://cmac.tv/newoncmac/

But I don't think WordPress is currently getting the necessary data to do this. There's the schedule data, but no way to query by first run, right?  It wouldn't know the first run from any other scheduled run.  

Probably requires modifications to the schedule sync code to bring over `FirstRuns` data from Cablecast.  Unfortunately this is beyond my abilities. Anyone want to take a stab at that? ChatGPT? :)

**Comment by bryanharley** [comment]
Sorry, just realized this is less of an "issue" and more of a feature request. Feel free to close and I can post under "Discussions".

**Comment by raytiley** [comment]
@bryanharley - It's fine here. You should be able todo this with the existing schedule function as an example. This should give you runs in your schedule that are airing in the provided time range for the first time.

```
function cablecast_get_schedules($channel_id, $date_start, $date_end) {
  global $wpdb;
  $table = $wpdb->prefix . 'cablecast_schedule_items';
  
  $sql = $wpdb->prepare("
    SELECT * 
    FROM $table 
    WHERE channel_id = %d 
      AND run_date_time >= %s 
      AND run_date_time <= %s 
      AND NOT EXISTS (
        SELECT 1 
        FROM $table as earlier 
        WHERE earlier.show_id = $table.show_id 
          AND earlier.run_date_time < %s
      )
    ORDER BY run_date_time ASC", 
    $channel_id, $date_start, $date_end, $date_start);

  // Execute the query and return the results
  return $wpdb->get_results($sql);
}
```

**Comment by bryanharley** [comment]
Clearly I don't know what I'm talking about. Thanks @raytiley, I'll give it a try!

**Comment by bryanharley** [comment]
@raytiley I'm seeing some duplicates shows. Any idea why? Test link: https://cmac.tv/new/

I'm doing: 

`      
$channel_id = 1;
$date_start = date('Y-m-d');
$date_end = date('Y-m-d', strtotime($date_start . "+7days"));
 
$schedule_content = "";
      
$schedule_itmes = cablecast_get_first_runs_schedules($channel_id, $date_start, $date_end);
  
      if(!empty($schedule_itmes)){
       foreach($schedule_itmes as $item) {
        $show_link = get_post_permalink($item->show_post_id);
        if (empty($show_link)) { continue; }
        $time = date('l, F j, Y - h:i a', strtotime($item->run_date_time));
        $title = $item->show_title;
        $schedule_content .= "<p><a href=\"$show_link\">$item->show_title</a><br />$time</p>";
       }
       }
       else{ $schedule_content .= "<p>No schedule available.</p>"; }
      $schedule_content .= "";
      return $schedule_content;
`

**Comment by bryanharley** [comment]
I fixed it by rewriting the SQL query a little differently:

```
SELECT * 
FROM $table AS current_item
WHERE channel_id = %d 
  AND run_date_time >= %s 
  AND run_date_time <= %s 
  AND NOT EXISTS (
    SELECT 1 
    FROM $table AS earlier 
    WHERE earlier.show_id = current_item.show_id 
      AND earlier.run_date_time < current_item.run_date_time
  )
ORDER BY run_date_time ASC
```

**Comment by raytiley** [comment]
@bryanharley  - cool, I'm not quite sure what your additional clause does, but my query would return all the shows and there air times. So you would need to de-duplicate by show maybe?

**Comment by bryanharley** [comment]
The results: [cmac.tv/newoncmac](https://cmac.tv/newoncmac)

Thanks!
